winget install -e --id 7zip.7zip
winget install -e --id Amazon.Games
winget install -e --id AnyDeskSoftwareGmbH.AnyDesk
winget install -e --id Bitwarden.Bitwarden
winget install -e --id code52.Carnac
winget install -e --id Discord.Discord
winget install -e --id Docker.DockerDesktop
winget install -e --id ElectronicArts.EADesktop
winget install -e --id EpicGames.EpicGamesLauncher
winget install -e --id Git.Git
winget install -e --id GOG.Galaxy
winget install -e --id Google.Chrome
winget install -e --id Google.CloudSDK
winget install -e --id JanDeDobbeleer.OhMyPosh
winget install -e --id LINQPad.LINQPad.7
winget install -e --id LogMeIn.LastPass
winget install -e --id Microsoft.AzureDataStudio
winget install -e --id Microsoft.DotNet.SDK.5
winget install -e --id Microsoft.DotNet.SDK.6
winget install -e --id Microsoft.DotNet.SDK.7
winget install -e --id Microsoft.dotNetFramework
winget install -e --id Microsoft.dotnetUninstallTool
# winget install -e --id Microsoft.Office
winget install -e --id Microsoft.PowerShell
winget install -e --id Microsoft.PowerToys
winget install -e --id Microsoft.RemoteDesktopClient
winget install -e --id Microsoft.Teams
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id Microsoft.WindowsPCHealthCheck
winget install -e --id Microsoft.WindowsTerminal
winget install -e --id Mozilla.Firefox.DeveloperEdition
winget install -e --id NickeManarin.ScreenToGif
winget install -e --id Notion.Notion
winget install -e --id Nvidia.GeForceExperience
winget install -e --id OpenJS.NodeJS
winget install -e --id Postman.Postman
winget install -e --id SlackTechnologies.Slack
winget install -e --id SonicWALL.NetExtender
winget install -e --id Spotify.Spotify
winget install -e --id SteelSeries.GG
winget install -e --id TablePlus.TablePlus
winget install -e --id Ubisoft.Connect
winget install -e --id Valve.Steam
winget install -e --id VideoLAN.VLC
winget install -e --id Yarn.Yarn

winget install -e --name "Alpine WSL"